cds-snc/scan-websites

architecture-decision-records/0001-api-framework-choice.md

Closes #3 by adding an architecture decision record for why we are using Fast API

docs: Fast API ADR

---

.github/workflows/ci_build.yml
api/Dockerfile

Currently our alpine optimized image of the API is missing the ability to compile the driver for postgres.

fix: add alpine dependencies for pg driver

---

terragrunt/aws/api/lambda.tf

Tunes the lambda to exit after 60 seconds and increases the memory available

fix: tune lambda

---

terragrunt/aws/api/rds.tf
terragrunt/aws/api/vpc.tf

Adds a nacl so the default nacl doesn't keep acquiring the subnets
Adds an engine version to instance which should fix issue of not being
able to find postgresql error

fix: fix issues with rds and default nacl

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

This PR fixes the creation of the zshrc file so it correctly goes to the
/home/vscode/.zshrc file instead of /home/.zshrc. It also configures
VSCode to use zsh in the devcontainer by default instead of bash.

Fixup zsh in devcontainer.

---

terragrunt/aws/api/rds.tf

- Should fix the issue with being unable to connect to the proxy
- RDS module now exposes a security group that allows 5432 to proxy and
rds

fix: upgrade RDS Module

---

.github/workflows/ci_code.yml
Makefile
api/main.py
api/tests/test_main.py
scanners/axe-core/src/common/foreach.ts
scanners/axe-core/src/impl.test.ts
scanners/axe-core/src/impl.ts

This PR updates the top level makefile to generate targets for each of
the [resource, command] pairs. The commands then invoke the relevant
targets for each resources. This allows make to correctly handle an error
in one of the targets and exit.
Fixes #45

Use targets instead of for loop in top level makefile.

---

terragrunt/aws/api/kms.tf
terragrunt/aws/api/s3.tf
terragrunt/aws/api/sns.tf

This PR adds an S3 bucket to the infrastructure to collect axe-core reports. It also adds a SNS topic that will send URLs to be scanned by axe-core.

feat: add S3 bucket for axe core reports and SNS queue for axe-core-urls

---

.devcontainer/docker-compose.yml
.github/workflows/scripts/run_shellcheck.sh
.github/workflows/shellcheck.yml
.github/workflows/tf_apply.yml
.github/workflows/tf_plan.yml
api/Dockerfile
api/main.py
bin/api_healthcheck.sh
bin/api_migrate.sh
bin/api_version.sh
scanners/axe-core/Dockerfile

- clean up the docker compose file
- add scripts to execute the lambda endpoints in the api service
- download a pinned version of the aws-lambda-rie Executable
- add some logging of env variables to the api
- add shellcheck as a ci check

feat: add api to docker compose network

---

terragrunt/aws/api/outputs.tf
terragrunt/aws/api/s3.tf
terragrunt/aws/scanners/axe-core/iam.tf
terragrunt/aws/scanners/axe-core/inputs.tf
terragrunt/aws/scanners/axe-core/lambda.tf
terragrunt/env/scanners/axe-core/terragrunt.hcl

Adds the lambda to the axe-core scanner. The lambda is triggered through messages in an SNS queue and will write reports to an S3 bucket and also take a screenshot of the URL it visits.

feat: add axe-core scanner lambda

---

api/main.py
api/storage/storage.py
api/tests/storage/test_storage.py
api/tests/test_main.py
terragrunt/aws/api/lambda.tf
terragrunt/aws/scanners/owasp-zap/network.tf

This PR adds a trigger to the API lambda to be invoked if an S3 file is added to the axe-core-report-data bucket. The API will invoke, download the file and produce a sample log output. Ideally at this point the API would extract the summary data from the report, write a summary into the database and do whatever else is need for reporting.

feat: adds the S3 report trigger to the API and adds sample handling

---

terragrunt/aws/api/s3.tf

Closes #16 by adding a 30 day retention policy to reports and images. This affects only the raw data in reports as the DB should retain a summary of most data, which can be used for aggregation. Detailed reports would be gone after 30 days. We can tweak this based on need. 
Images would be lost forever after 30 days. 
This should clean up data if it is no longer useful, assuming things are no longer useful after 30 days.

feat: adds s3 expiry rules

---

api/db_migrations/versions/b9ab107cd56a_create_users_table.py
api/models/Organisation.py
api/models/User.py
api/models/__init__.py
api/requirements.txt
api/tests/models/test_Organisation.py
api/tests/models/test_User.py

Closes #69. Adds a `user` model based on the proposal in #9.

feat: user model

---

.devcontainer/devcontainer.json
.github/workflows/ci_code.yml

The python-test action is renamed to test as it runs more then just
python. The dev container is renamed to `Scan Websites` to make it
clearer which one you're working with.

Update some naming.

---

runners/owasp-zap/Dockerfile
scanners/owasp-zap/Dockerfile

Pip install of awscli was resulting in the runner-owasp-zap image being > 2 GB. Downloading the zip from aws and copying it to the bin path allows the image sizes to be reduced significantly.

chore: reduce zap image size

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
api/Dockerfile
api/bin/entry.sh
api/requirements.txt
api/requirements_playwright.txt

This PR does a couple of things.
First it reworks the Dockerfile for the API so that it runs expensive commands first so we can take advantage of caching.
For instance it will install playwright and chromium up front since those are slow and as it stands will always re-run whenever files change.
Secondly it installs the python modules in a different folder then the api code and sets the `PYTHONPATH` env variable to that folder so that we can mount the `api` folder as a volume mounted to `/function/` in the container.
Thirdly it installs `entr` and uses that to watch for changes to all *.py files in the api folder and subdirectories, when those files change it will restart aws-lambda-rie.
Closes #91
Run the branch in a devcontainer, make a change to the python code, hit the endpoint and …

feat: Hot reload python files when running locally

---

.devcontainer/devcontainer.json
api/database/migrate.py
api/db_migrations/alembic.ini
api/tests/conftest.py

Adds a SQL tool to the dev container which shortcuts psql and gives you some more options to work with the DB.
Also fixes a bug where you could not run migrations both from the make file and the code.

feat: sql tool and make migrations fix

---

api/db_migrations/versions/da6527f6cd76_create_scan_types_table.py
api/models/ScanType.py
api/tests/models/test_ScanType.py

Adds the `ScanType` model based on the design in #9 - we may want to look at a seeding script.

feat: add ScanType model

---

api/db_migrations/versions/bf6d44121dce_create_templates_table.py
api/models/Template.py
api/tests/conftest.py
api/tests/models/test_Template.py
api/tests/models/test_User.py

This PR adds the `Template` model as defined in #9.

feat: add Template model

---

api/db_migrations/versions/e6ec4f01db2f_create_template_scans_table.py
api/models/ScanType.py
api/models/Template.py
api/models/TemplateScan.py
api/tests/conftest.py
api/tests/models/test_TemplateScan.py

This PR adds the `TemplateScan` model as defined in #9.

feat: add TemplateScan model

---

api/db_migrations/versions/06b310a6251e_create_organisations_table.py
api/db_migrations/versions/b9ab107cd56a_create_users_table.py
api/db_migrations/versions/bf6d44121dce_create_templates_table.py
api/db_migrations/versions/da6527f6cd76_create_scan_types_table.py
api/db_migrations/versions/db98eafe1333_create_template_scan_triggers_table.py
api/db_migrations/versions/e6ec4f01db2f_create_template_scans_table.py
api/models/TemplateScan.py
api/models/TemplateScanTrigger.py
api/tests/conftest.py
api/tests/models/test_TemplateScanTrigger.py

This PR adds the `TemplateScanTrigger` model defined in #9. The only change was from the `callback:string` to `data:jsonb` field. Because we are not sure what that `callback` mechanism looks like, we can just keep it ambiguous as a `data` map.

feat: add template scan trigger model

---

api/db_migrations/versions/eb58f2b364a3_create_scans_table.py
api/models/Organisation.py
api/models/Scan.py
api/models/ScanType.py
api/tests/conftest.py
api/tests/models/test_Scan.py
api/tests/models/test_Template.py
api/tests/models/test_TemplateScan.py
api/tests/models/test_TemplateScanTrigger.py
api/tests/models/test_User.py

This PR adds the `Scans` model as defined in #9. It also adds some more checks to existing model tests around missing relationship dependencies and makes sure order or import issues with the fixtures don't cascade into the tests.

feat: add scans model

---

.github/workflows/tf_apply.yml
.github/workflows/tf_plan.yml
terragrunt/aws/hosted_zone/hosted_zone.tf
terragrunt/aws/hosted_zone/inputs.tf
terragrunt/aws/hosted_zone/outputs.tf
terragrunt/env/hosted_zone/terragrunt.hcl

This creates a hosted zone named `scan-websites.alpha.canada.ca` that will be used to manage the scan websites DNS records.
Closes #117  
Related #118

feat: add Route53 hosted zone

---

api/api_gateway/api.py
terragrunt/aws/api/api_gateway.tf
terragrunt/aws/api/certificate.tf
terragrunt/aws/api/inputs.tf
terragrunt/aws/api/route53.tf
terragrunt/env/api/terragrunt.hcl

This creates a custom domain name, certificate and DNS "A" record for `scan-websites.alpha.canada.ca`.
Closes #118

feat: API stage custom domain and certificate

---

terragrunt/aws/api/lambda.tf
terragrunt/aws/api/vpc.tf

Closes #121. Cann't authenticate with google if egress on port 443 is blocked. This PR will now allow the lambda api to connect externally to https services

fix: allow lambda api to egress on port 443

---

scanners/axe-core/src/impl.test.ts
scanners/axe-core/src/impl.ts
scanners/axe-core/src/index.ts

This PR fixes an access issue to the S3 screenshot bucket. We agreed not to have a public bucket and just front the assets through Cloudfront at a later point in time.

fix: remove public read on screenshots

---

terragrunt/aws/api/api_gateway.tf

Attempt 2 to fix the scan-websites.alpha.canada.com/ root path loading. Closes #124.

fix: attach to correct root method

---

.github/workflows/ci_code.yml

* Add the `terragrunt` folder to the matrix jobs to lint and format check the code.
* Add a check for changes within each matrix folder to exit early if there's no new code.
**Note:** although it would work to remove the `matrix` and use the root level `Makefile` to execute the workflow steps, using a matrix approach is faster as each folder will run in parallel.
Related #132

feat: add Terragrunt to `Lint` GitHub workflow

---

api/api_gateway/api.py
api/api_gateway/custom_middleware.py
api/api_gateway/routers/auth.py
api/tests/api_gateway/test_api.py
api/tests/conftest.py
terragrunt/aws/api/api_gateway.tf

First attempt to [set hsts at the api gateway](https://github.com/cds-snc/scan-websites/runs/3725043252) failed due to proxy integrations not allowing transforming responses. `Proxy integrations cannot be configured to transform responses`
This PR will move that functionality to fastapi via custom middleware.

fix: move hsts functionality from api gateway to application layer

---

terragrunt/.checkov.yml
terragrunt/aws/api/api_gateway.tf
terragrunt/aws/api/cloudwatch.tf
terragrunt/aws/api/ecr.tf
terragrunt/aws/api/kms.tf
terragrunt/aws/api/lambda.tf
terragrunt/aws/scanners/axe-core/ecr.tf
terragrunt/aws/scanners/axe-core/iam.tf
terragrunt/aws/scanners/axe-core/lambda.tf
terragrunt/aws/scanners/owasp-zap/ecr.tf
terragrunt/aws/scanners/owasp-zap/ecs.tf
terragrunt/aws/scanners/owasp-zap/lambda.tf

This includes the following fixes:
* enable API gateway access logs
* enable Lambda X-ray tracing for debug
* use common Terragrunt vars for KMS policy
* add IAM policy `sid` to stop policy flapping in plans
The last outstanding warning for a WAF ACL will be handled by #142.
Closes #132

fix: checkov warnings with Terraform

---

terragrunt/.checkov.yml
terragrunt/aws/api/api_gateway.tf
terragrunt/aws/api/waf.tf

Associate a Web Application Firewall Access Control List with
the API to protect it from malicious input.
Also provides a rate limit of 100 requests from the same IP in a
5 minute period (the minimum allowed by a rate limit statement).
If these needs to be lower, we can add multiple rate limit statements.
Related #111
Closes #142

feat: add WAF ACL for API

---

terragrunt/aws/api/waf.tf

The `GenericRFI_QUERYARGUMENTS` rule is blocking login with Google accounts.
Related #142

fix: exclude AWS common rule

---

api/api_gateway/routers/scans.py
api/requirements.txt
api/tests/api_gateway/test_api.py

IP based rate limiting has been added by the WAF ACL in #144.
Closes #111

fix: remove slowapi rate limiting

---

.github/workflows/tf_plan.yml
api/api_gateway/routers/scans.py
api/tests/api_gateway/test_scans.py
terragrunt/aws/api/waf.tf

Topic arn was not being retrieved from environment variable and currently getting block by RFI_BODY WAF rule when creating new scans.

fix: topic arn and unblock url when creating scans

---

terragrunt/aws/api/iam.tf

API currently can't publish to ZAP topic

fix: allow api to publish to zap topic

---

terragrunt/aws/api/iam.tf
terragrunt/aws/api/kms.tf

Grant the API access to kms in-order to publish to encrypted sns topic. Applied locally to test

feat: allow api to decrypt kms used for sns topics

---

api/front_end/view.py
terragrunt/aws/api/waf.tf

Remove all schema data attributes that automagically add a `None`. Also expands the WAF rules to include exceptions PU requests for template scan updates.

fix: schema validation and WAF regex

---

api/api_gateway/routers/scans.py
api/db_migrations/versions/ee2ca4ffaee4_cleanup_orphaned_scans.py
api/front_end/templates/index.html
api/models/Scan.py
api/tests/api_gateway/test_scans.py
api/tests/conftest.py

- Alembic script to cleanup orphaned scans
- Remove view scan link for unauthenticed users
- Delete template scan endpoint will now delete associated scans
- A11yReport and SecurityReports are now sorted by update timestamp descending

feat: delete associated scans when template deleted

---

api/api_gateway/custom_middleware.py
api/front_end/templates/index.html
api/front_end/templates/scan_results_a11y.html
api/front_end/templates/scan_results_security.html

- Scan headers are currently backwards
- link to the template view from index page
- Bump HSTS header max-age so continue testing
Closes #139

fix: scan table correct headers

---

api/crawler/crawler.py
api/tests/crawler/test_crawler.py

Adds the known set of working chromium flags that seem to work on Lambda

fix: provide chrome args for playwright

---

.github/workflows/tf_apply.yml
.github/workflows/tf_plan.yml
terragrunt/aws/alarms/cloudwatch_breakglass.tf
terragrunt/aws/alarms/cloudwatch_lambda.tf
terragrunt/aws/alarms/inputs.tf
terragrunt/aws/alarms/notify_slack.tf
terragrunt/aws/api/outputs.tf
terragrunt/env/alarms/terragrunt.hcl

Creates a new `alarms` module that will contain CloudWatch
Alarms and the Lambda function responsible for posting the alarm
state changes to an ops Slack channel.
For consistency, the `ops` breakglass login alarms were moved
to the new module.
- Closes #154

feat: add CloudWatch Alarm Slack notifications

---

api/front_end/static/js/template_scan.js
api/front_end/templates/template_scan.html

Closes #191 by moving the header out of the div. The original reason for implementing the header through JS was that when clicked clear, it would remove the header, but when you added the header through the add button, you got two headers.

fix: duplicate header

---

terragrunt/env/scanners/owasp-zap/container-definitions/zap_runner.json

OWASP Zap is running out of disk space, which is currently set to the default ECS amount of 20GB. This PR will increase the zap task to 40GB in-order to avoid running into disk space issues when scanning larger webapps.

fix: increase zap scanners ephemeral storage to 40 GB

---

terragrunt/env/orchestrator/state-machines/dynamic-security-scans.json

State machine definition isn't referencing the correct items in the payload array.
No change to plan since i tested/debugged using the console.

fix: state function match scan type

---

api/pub_sub/pub_sub.py
terragrunt/env/orchestrator/state-machines/dynamic-security-scans.json

Nuclei enum doesn't match what's in database.

fix: nuclei type name has wrong case

---

terragrunt/aws/api/lambda.tf

Revert lambda layer for aws otel collector

fix: remove lambda layer for aws otel collector

---

.gitignore
api/Dockerfile

Also included: 
update gitignore  
add otel tracing variable to lambda tf
Added code from AWS Otel lambda layer to docker image in ecr. We then pull that image in to run it directly in the app since layers are not available for lambdas using containers. (Yet, presumably they will add this function à la Honeycomb et al.)

feat: add aws otel lambda as docker image 

---

terragrunt/aws/api/lambda.tf

Re-enables the AWS Lambda exec wrapper environment variable to use the `otel-instrument` binary to execute requests.

fix: add AWS Lambda exec wrapper env variable

---

api/api_gateway/routers/scans.py
api/crawler/crawler.py
api/front_end/templates/index.html
api/front_end/templates/scan_results_a11y.html
api/requirements.txt
api/requirements_dev.txt
api/tests/api_gateway/test_scans.py
api/tests/crawler/test_crawler.py

Closes #255
- Fixes dispatch that has been broken since the pub_sub functionality was refactored to accept a list of payloads to dispatch.
- Crawl moved into a async function
- Error handling added to a11y views

fix: a11y scans thread and dispatch issue resolved

---

.github/workflows/build_and_push.yml
.github/workflows/ci_build_continers.yml
.gitignore
api/Dockerfile
bin/retrieve_otel_layer.sh

Instead of using a prebuilt docker image, download the contents of the lambda layer instead.

feat: retrieve lambda layer on build

---

api/Dockerfile
api/Dockerfile.heroku
api/main.py
api/requirements.txt

AWS lambda opentelemetry auto instrumentation assumes that you're setup exactly the same as lambda runtime environments (either using lambda layers or container images).
Migrating to using the amazon/lambda-python will make it less work to maintain observability in the future or to leverage new tools that work in lambda.

fix: working opentelemetry

---

api/requirements.txt

Auto instrumentation is trying to instrument sqlalchemy but the dependencies haven't been included.

feat: auto instrument support for sqlalchemy

---

api/Dockerfile
api/bin/entry.sh

The missing link to the autoinstrumentation of our original docker image was the call to the python wrapper defined using the `AWS_LAMBDA_EXEC_WRAPPER` environment variable. This bootstraps the lambda handler invocation so that opentelemetry can create begin and end spans when the lambda starts and to detect all loaded python libraries that support auto instrumentation.

feat: debian based opentelemetry autoinstrumentation

---

.devcontainer/Dockerfile
api/api_gateway/api.py
api/api_gateway/custom_middleware.py
api/api_gateway/middleware/security_headers.py
api/crawler/crawler.py
api/front_end/view.py
api/requirements_dev.txt
api/tests/api_gateway/test_api.py
api/tests/conftest.py
api/tests/crawler/test_crawler.py

When the security headers middleware was introduced that caused the background tasks to no longer run in the background since it was being blocked by the middleware. This is due to https://github.com/encode/starlette/issues/919. Moving towards a custom middleware class that uses pure ASGIApp resolves the issue.
Using this class also fixed the issue were the middleware wasn't working well in the CI environment and needed customization in-order to run tests.
Background tasks should work as expected and an immediate response received when scans are started.

fix: background no longer blocked by middleware

---

api/collector.yaml

Reduce logging to default levels now that opentelemetry instrumentation is working as expected.

chore: disable debug logs

---

api/crawler/crawler.py
api/requirements.txt
api/tests/crawler/test_crawler.py

Now that the background task has been fixed, the uvloop custom asyncio event loop for scrapy is no longer required since background task will automatically create a new event loop for the crawl to run in.

chore: remove uvloop event loop; no longer required

---

api/crawler/crawler.py
api/database/seed.py
api/front_end/templates/scan_results_a11y.html
api/requirements.txt
api/storage/storage.py
api/tests/crawler/test_crawler.py

- Crawler occasionally blocks the main thread which will cause the scan request to timeout at the apigateway. Running the crawl in a dedicated thread should make the results more consistent.
- Minor tweaks to the a11y views so that scans that failed can be deleted. Currently only reports with results are visible, so you can't delete bad scans

feat: run crawler in its own thread

---

terragrunt/aws/tf_roles/main.tf

Add roles so that the plan OIDC role can access state bucket and Lock Table.
Closes #283

feat: add TG IAM Roles for OIDC

---

terragrunt/aws/tf_roles/main.tf

Unfortunately i copied and pasted from the TG Docs and forgot to change the ARN from a generic one.

fix: use the proper ARN for dynamodb table

---

terragrunt/aws/tf_roles/main.tf

The plan is failing on refreshing state because ReadOnlyAccess denies access to secrets (For good reason).

fix: allow tf plan to read secrets

---

terragrunt/aws/api/api_gateway.tf
terragrunt/aws/api/iam.tf
terragrunt/aws/api/waf.tf

Adds missing IAM policies that was preventing WAF ACL logs from being written to S3

fix: firehose write to s3 missing iam permissions

---

terragrunt/aws/api/vpc.tf

Test vpc flow logs prefix. [According to AWS logs it should be possible to a prefix when defining the bucket name](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs-s3.html)

chore: add prefix for vpc flow logs

---

scanners/axe-core/package-lock.json
scanners/axe-core/package.json
scanners/axe-core/src/impl.test.ts
scanners/axe-core/src/impl.ts

S3 was automatically encoding the `:` in the UTC time of filenames, resulting in errors when the api attempts to retrieve axe-core report data. Moving from UTC time to epoch time as a unique identifier will ensure no special characters exist in filenames.
Also upgrading aws-sdk from 2.1054.0 to 2.1055.0 to resolve a Snyk reported vulnerability.

fix: UTC time was causing inconsistent filenames

---

api/front_end/templates/scan_results_nuclei_summary.html
api/i18n/en.json
api/i18n/fr.json
api/storage/storage.py
api/tests/storage/test_storage.py

Nuclei output has some optional outputs that are not consistent. This PR will validate before trying to store some of the optional fields.

fix: validate before referencing optional fields

---

terragrunt/aws/api/lambda.tf

Processing of nuclei reports when written to S3 was never enabled. 😵‍💫

feat: enable missing s3 monitoring for nuclei reports

---

terragrunt/env/common/provider.tf

Pin AWS provider to version 3 in-order to prevent breaking changes.

feat: pin tf provider to v3

---

.github/workflows/start_scan.yml

Re-useable "start scan" workflow so that onboarded products all stay in sync if the process to start scans change in the future.

feat: common workflow to launch scans

---

.github/workflows/start_scan.yml

Change secrets input to lowercase and remove reference to static scan in job name

fix: typo and lowercase secrets input

---

.github/workflows/generate_sbom.yml

Add GitHub workflow to generate SBOMs for the API and
axe-core scanner.
* cds-snc/platform-sre-security-support#94

feat: generate API and axe-core SBOM

---

terragrunt/aws/api/rds.tf

This PR upgrade the postrgres engine to 13.6 in which case we can add a serverless reader and switch to serverless.

chore: upgrade postgres to 13.6

---

terragrunt/aws/api/rds.tf

Go to 13.4 first :( 
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_UpgradeDBInstance.PostgreSQL.html#USER_UpgradeDBInstance.PostgreSQL.MajorVersion

chore: upgrade postgres to 13.4

---

.github/workflows/build_and_push.yml
.github/workflows/ci_build_continers.yml
.github/workflows/generate_sbom.yml

Update the SBOM workflows to use the `v1` git SHA for the GitHub action.

chore: pin Generate SBOM GitHub action to v1 SHA

---

.github/workflows/build_and_push.yml
.github/workflows/ci_build_continers.yml
.github/workflows/generate_sbom.yml

This provides a fix for the slow `docker sbom` creation.
* cds-snc/platform-sre-security-support#94

chore: update to latest generate-sbom action

---

.devcontainer/docker-compose.yml

Closes #343
Sets the platform for the Docker Containers to amd64 so that platforms running arm64 don't try to override the platform (and thus don't work)
Run Dev env on arm64 device, and it will no longer be mad about dependencies that aren't available on arm64.

* Add platform enforcement to support ARM chips.

---

.devcontainer/docker-compose.yml

Currently the api, database and test database containers remain active after the devcontainer is closed. This is due to the docker compose restart policy. Changing it to `unless-stopped` will prevent these services from being restarted when the devcontainer issues a [stop command](https://github.com/cds-snc/scan-websites/blob/5dec17f59f6a032940dcbc37bf367990d075c9e6/.devcontainer/devcontainer.json#L8)

feat: only restart services if devcontainer not stopped

---

.devcontainer/devcontainer.json
terragrunt/aws/api/rds.tf

Upgrade RDS cluster to latest `aurora-postgresql` engine version.
Also adds a quality of life fix to the devcontainer so that Terraform code
is formatted on save.

chore: upgrade RDS to postgres 14.3

---

terragrunt/aws/api/lambda.tf
terragrunt/aws/api/rds.tf

Update the Serverless V2 ACUs so that upgrades can be performed properly.
Also updates to Postgres `14.3`.

fix: update database ACU and major version

---

terragrunt/aws/api/rds.tf

Increase the RDS cluster's ACU in prep for an upgrade (values recommended by AWS suppport).
Without this increase, the upgrade gets stuck in an inconsistent "upgrade" state.
- This PR should also include a `14.3` engine upgrade which previously failed to apply.
- The ACU bump was performed in the cluster to allow a minor patch update.

chore: bump serverless ACU for upgrades

---

.github/workflows/export_github_data.yml

Update GitHub exporter workflow to include checkout step.
- cds-snc/platform-core-services#204

fix: add checkout to GitHub exporter workflow

---

renovate.json

overriding Renovate configs to test issue with PR creation

fix: pr creation to start immediate
