.github/workflows/build_and_push.yml
.github/workflows/tf_apply.yml

Fixes a directory problem in the continuous deployment for tf_apply and pushing the lambda containers

fix: correctly set dirs for CD on deploy and tf apply

---

terragrunt/aws/api/vpc.tf
terragrunt/env/common/common_variables.tf
terragrunt/env/terragrunt.hcl

- add a high availability vpc
- add a cost centre code

feat: add vpc and cost-centre-code

---

.github/workflows/tf_apply.yml
terragrunt/aws/api/vpc.tf

Adds the ability to auto approve applys
Adds a NSG that will be used by RDS module this needs to be created first.

feat: add auto approve and nsg

---

.github/workflows/tf_apply.yml

> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.
---
> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.
> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de …

fix: add password to apply workflow

---

terragrunt/env/api/terragrunt.hcl

> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.
---
> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.
> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de …

fix: use a non-reserved username

---

terragrunt/aws/api/rds.tf

The RDS password has also been updated in github secrets for this
release.

fix: update to v0.0.10 which fixes secret name and adds proxy logging

---

api/Dockerfile
terragrunt/aws/api/rds.tf
terragrunt/aws/api/vpc.tf

- Adds a security group to the lambda and connects it to the rds sg
- Add a missing library to the image
**Please Note** This TF change has already been applied

feat: add a sg to the lambda, fix docker issue

---

api/database/db.py

Postgresql connect_args documentation is here: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS

feat: add a database connection timeout

---

.devcontainer/Dockerfile

This PR updates the devcontainer to have the postgresql client providing
the `psql` command in the container.

Add postgresql-client to dockerfile.

---

terragrunt/aws/api/iam.tf
terragrunt/aws/api/lambda.tf

Adds a role for the lambda
Attachs the lambda to the vpc and private subnets

feat: attach lambda to vpc

---

terragrunt/aws/api/lambda.tf
terragrunt/aws/api/rds.tf
terragrunt/aws/api/vpc.tf

- Removes old security groups
- Adds the proxy and the labmda to the same sg
- Upgrade the modules to the latest version

feat: put lambda and RDS proxy in the same module

---

terragrunt/aws/api/rds.tf

- upgrade adds an egress rule to the security group created by the RDS
module.

fix: upgrade rds module

---

.github/workflows/build_and_push.yml
.github/workflows/scripts.yml
.github/workflows/scripts/run_shellcheck.sh
.github/workflows/scripts/test/error_response.json
.github/workflows/scripts/test/success_response.json
.github/workflows/scripts/test_migration_resp.sh
.github/workflows/scripts/test_scripts.sh
api/database/migrate.py
api/db_migrations/alembic.ini
api/main.py
api/tests/conftest.py
api/tests/test_main.py

- Watches for a custom migrate task and runs the db migration if found
- Adds a step to the build and push workflow to run a migration after
the lambda is deployed
- Adds a script to test the repsonse of that migration invocation
- Adds a workflow that will run shellcheck and some tests on our scripts
Closes #30

feat: add db migrations

---

.github/workflows/build_and_push.yml
scanners/axe-core/Dockerfile
scanners/axe-core/src/common/browser.ts
scanners/axe-core/src/impl.test.ts
scanners/axe-core/src/impl.ts
scanners/axe-core/src/index.ts

Adds continuous deployment for the axe-scanner and add fixes to the screenshot function.

feat: add CD for axe-core-scanner and fix some code issues

---

.devcontainer/devcontainer.json
terragrunt/aws/api/alarms.tf
terragrunt/aws/api/sns.tf

- Also adds the terraform extension to the dev container

feat: add a user alarm for ops1 and ops2

---

terragrunt/aws/api/outputs.tf

Output VPC and Subnet to be used by other modules

feat: output vpc and subnets for future zap scanning infrastructure

---

.github/workflows/build_and_push.yml

Typo in github action. Missing closing round bracket.

fix: typo in github action

---

.github/workflows/build_and_push.yml
terragrunt/aws/scanners/owasp-zap/lambda.tf

Subscribe to SNS topic for zap url scanning and remove whitespace from shell assignment when creating image name.

feat: sub to zap topic and fix script in action

---

.github/workflows/build_and_push.yml
.github/workflows/ci_build_continers.yml

GitHub automatically evaluates the if conditional as an expression.

chore: remove expression syntax from github action if conditions

---

Makefile
api/Makefile
terragrunt/Makefile

Adds missing .PHONY targets
Add doc for lint-ci

fix: address comments missed in an earlier PR, minor issues only

---

.github/workflows/scripts/migrate.sh
.github/workflows/scripts/run_shellcheck.sh
.github/workflows/scripts/test_scripts.sh

This PR updates the various bash scripts to add the [strict bash](http://redsymbol.net/articles/unofficial-bash-strict-mode/) settings.

Add strict bash lines to files.

---

.github/workflows/tf_apply.yml
.github/workflows/tf_plan.yml
api/Makefile
api/api_gateway/api.py
api/api_gateway/routers/auth.py
api/api_gateway/routers/ops.py
api/api_gateway/routers/organisations.py
api/database/db.py
api/db_migrations/README.md
api/db_migrations/versions/5818f4679595_seed_databases.py
api/front_end/templates/base.html
api/front_end/templates/index.html
api/front_end/templates/login.html
api/front_end/view.py
api/i18n/en.json
api/i18n/fr.json
api/models/User.py
api/requirements.txt
api/tests/api_gateway/test_api.py
api/tests/conftest.py
api/tests/models/test_User.py
terragrunt/.checkov.yml
terragrunt/aws/api/inputs.tf
terragrunt/aws/api/lambda.tf

Closes #110. 
Changes
- Login via Gsuite implemented. Can only be used by cds-snc google workspace members.
- Database will be seeded with a CDS org and a accessibility + security scan types
- password_hash in user database now allows null since users can login via gsuite

feat: gsuite login and route protection

---

scanners/axe-core/src/impl.ts
scanners/axe-core/src/index.ts

Adds some debug logging to the axe-core scanner

fix: add more logging

---

terragrunt/aws/api/api_gateway.tf

Closes #124. The api gateway will now route / requests to the lambda for processing. Should result in the index page being loaded.

fix: route root path requests to the lambda api

---

terragrunt/aws/api/api_gateway.tf

integration_http_method was incorrectly set to GET. It's now POST...

fix: change integration method to correct one

---

.devcontainer/docker-compose.yml
.devcontainer/scripts/init_localstack/localstack-entrypoint.sh
README.md
api/storage/storage.py
api/tests/storage/fixtures/owasp_zap_report.json
api/tests/storage/test_storage.py
bin/api_create_organisation.sh
bin/api_healthcheck.sh
bin/api_version.sh
bin/scanner_zap_s3_put_test.sh
runners/owasp-zap/entrypoint.sh
scanners/owasp-zap/src/impl.test.ts
scanners/owasp-zap/src/impl.ts

owasp zap reports will now be processed and stored in the database. Triggered by S3 put

feat: store zap reports to db, triggered by s3 put

---

api/api_gateway/routers/scans.py
api/front_end/static/js/template.js
api/front_end/templates/index.html
api/front_end/templates/scan_results_security.html
api/front_end/templates/template_scan_list.html
api/i18n/en.json
api/i18n/fr.json
api/tests/api_gateway/test_scans.py
api/tests/conftest.py

feat: delete report button

---

api/database/seed.py
api/storage/storage.py
api/tests/storage/test_storage.py

Redo seeding so that storage.py is reused which will reproduce real scan results.

feat: reuse storage module to seed database

---

terragrunt/aws/orchestrator/ecr.tf

fix: point to correct ecr name

---

.devcontainer/docker-compose.yml
.devcontainer/scripts/init_localstack/localstack-entrypoint.sh
orchestrator/src/impl.test.ts
orchestrator/src/impl.ts
orchestrator/src/index.ts
runners/nuclei/entrypoint.sh
runners/owasp-zap/entrypoint.sh
terragrunt/aws/api/iam.tf
terragrunt/aws/api/outputs.tf
terragrunt/aws/api/sns.tf
terragrunt/aws/orchestrator/ecs.tf
terragrunt/aws/orchestrator/iam.tf
terragrunt/aws/orchestrator/lambda.tf
terragrunt/aws/orchestrator/task_execution_policy_documents.tf

fix: task def unique family

---

orchestrator/src/common/config.ts
orchestrator/src/impl.test.ts
orchestrator/src/impl.ts

- Enhancements to be able to specify unique inputs for each step. Leverage stepfunctions `InputPath` feature to specify which key the inputs for the step should scope to
- Use Nuclei report bucket
- IAM permission fixes

fix: iam and stepfunction input issues

---

orchestrator/src/common/record.ts
orchestrator/src/impl.test.ts
orchestrator/src/impl.ts
terragrunt/aws/orchestrator/ecs.tf

- Use scanner name in state machine
- Increase heartbeat to give enough time for ECS task to start

feat: stepfunction improvements

---

api/api_gateway/routers/scans.py
api/db_migrations/versions/ff660f256a86_migrate_zap_nuclei_to_step_function.py
api/pub_sub/pub_sub.py
api/tests/api_gateway/test_scans.py
api/tests/pub_sub/test_pub_sub.py
terragrunt/aws/api/iam.tf

🧪 Launch step functions from the API so that the lambda can be removed.

feat: api launch scanning state machine

---

.devcontainer/docker-compose.yml
api/front_end/scan_view.py
api/front_end/templates/scan_results_a11y.html
terragrunt/aws/api/iam.tf
terragrunt/aws/api/lambda.tf

This PR enables the link to screenshots on A11Y reports.

feat: adds a link to the S3 image bucket

---

README.md
api/pub_sub/pub_sub.py
api/tests/api_gateway/test_scans.py

Nuclei was missing the payload validator

fix: missing validator causing scan failure

---

api/front_end/scan_view.py

fix: Proper image key

---

api/front_end/scan_view.py

Currently the images are returning base64, they need to cast to bytes.

fix: cast to bytes

---

api/pub_sub/pub_sub.py
api/tests/pub_sub/test_pub_sub.py

Payload incorrectly getting jsonified (?)

fix: jsonify the whole payload

---

api/front_end/scan_view.py

This PR forcibly base64 decodes the image object

fix: force base64 decode

---

api/front_end/scan_view.py
api/front_end/templates/scan_results_a11y.html
api/front_end/templates/scan_results_screenshot.html

Embeds a screenshot in the website instead of messing with API Gateway content conversion and accept headers

feat: add screenshot into webpage

---

api/api_gateway/routers/scans.py
api/front_end/templates/scan_results_nuclei.html
api/front_end/templates/scan_results_owasp_zap.html
api/front_end/templates/template.html
api/front_end/view.py
api/models/Template.py
api/tests/api_gateway/test_scans.py

feat: delete template and minor bug fix

---

api/front_end/templates/scan_results_nuclei.html
api/front_end/templates/scan_results_owasp_zap.html
api/storage/storage.py

- Fixes total's when items are being processed and ignores are active
- Add back the button to view ignored items

fix: adjust total when results are filtered

---

api/database/seed.py
api/front_end/templates/index.html

Didn't account for the scenario when a new template scan is currently in-progress and results haven't come in yet.

fix: check if totals available before calculating delta

---

terragrunt/aws/api/outputs.tf
terragrunt/aws/api/sns.tf

feat: add an sns topic for github scanner

---

terragrunt/aws/api/lambda.tf

This should provide X-Ray tracing using AWS OpenTelemetry for
the Lambda API requests.
It was based on this setup guide:
https://aws-otel.github.io/docs/getting-started/lambda/lambda-python

feat: add AWS OpenTelemetry Lambda layer

---

terragrunt/env/orchestrator/state-machines/dynamic-security-scans.json

feat: move to next scan instead of failing entire execution chain

---

api/crawler/crawler.py
api/tests/crawler/test_crawler.py
scanners/axe-core/package.json

fix: create asyncio event loop for crawler and bump dependency version

---

api/api_gateway/routers/scans.py
api/pub_sub/pub_sub.py
api/storage/storage.py
api/tests/api_gateway/test_scans.py
api/tests/pub_sub/test_pub_sub.py
api/tests/storage/test_storage.py

feat: group reports crawled from same base domain

---

api/collector.yaml
terragrunt/aws/api/lambda.tf

Custom config so that debug can be enabled.

feat: use custom otel config with debug enabled

---

.github/workflows/tf_apply.yml
.github/workflows/tf_plan.yml
terragrunt/aws/tf_roles/main.tf
terragrunt/env/tf_roles/terragrunt.hcl

- Adds a role restriced to main branch that can has the admin managed
policy attached.
- Adds a role that has no branch restriction that has the readonly
managed policy attached
**Please Note:** I'm not 100% sure the readonly role will work so testing in a low risk repo. Also this is part 1 of 2 planned PR's the second will be changing the TF actions.

feat: add roles for tf plan and apply using OICD

---

scanners/axe-core/package-lock.json
scanners/axe-core/package.json
scanners/axe-core/src/impl.test.ts
scanners/axe-core/src/impl.ts

Fixes #278 
- Added timestamp to report and screenshot names
- Bumped jest so i could use the [new default fake timers](https://jestjs.io/blog/2020/05/05/jest-26#new-fake-timers)

fix: crawled items overwriting reports

---

terragrunt/aws/tf_roles/main.tf

Related to #280
This doesn't close it but is the first step needed so we can test it out.
Next will be a PR that removes the AWS Iam AUTH and converts to OIDC so we can test.

feat: update to v1.0.0 for gh_oidc_role module

---

.github/workflows/tf_apply.yml
.github/workflows/tf_plan.yml

Authenticates the Plan action using a readonly account and apply using
an admin account.

feat: use OpenID Connect to auth TF actions

---

terragrunt/aws/tf_roles/main.tf
terragrunt/env/tf_roles/terragrunt.hcl

This is to test the new module and the apply functionality of the OIDC role
Should close #280

feat: use the new tfplan module to add req policy

---

terragrunt/aws/api/iam.tf
terragrunt/aws/api/vpc.tf
terragrunt/aws/api/waf.tf
terragrunt/aws/tf_roles/main.tf
terragrunt/env/common/common_variables.tf
terragrunt/env/terragrunt.hcl

This will send VPC flow logs and WAF logs to the CBS satellite bucket in the account.

feat: add Cloud Based Sensor integration

---

terragrunt/aws/api/waf.tf

Update waf logging prefix to be consistent with other services

chore: consistent logging structure

---

terragrunt/.checkov.yml
terragrunt/aws/api/lambda.tf
terragrunt/aws/api/vpc.tf

This PR adds the source account to the lambda invoke permissions as an additional safeguard to invoking.

feat: adds account source to lambda invoke permissions

---

.github/workflows/build_and_push.yml
terragrunt/.checkov.yml
terragrunt/aws/api/lambda.tf
terragrunt/aws/api/rds.tf

fix: redeploy with new envs

---

.devcontainer/devcontainer.json
api/api_gateway/api.py
api/api_gateway/routers/scans.py
api/front_end/static/js/template_scan.js
api/front_end/templates/template_scan.html
api/front_end/view.py
api/requirements_dev.txt
api/schemas/Template.py
api/tests/api_gateway/test_scans.py

Refactored the template creation process to no longer accept key/value pairs from users. I've also introduced input fields that will accept urls that should not be scanned.

refactor: template creation

---

.github/workflows/tf_apply.yml
.github/workflows/tf_plan.yml

The PR sets up the CI/CD to use the new terraform tools setup action.

feat: Use terraform tools setup

---

terragrunt/aws/api/rds.tf

Sets `allow_major_version_upgrade`

chore: upgrade postgres to 13.4 (really now)

---

renovate.json

Migrate to the default cds renovate config

feat: use cds renovate config

---

README.md

Adds a small tweak to the readme.md for new devs.
N/A

* Update readme.md to help new Devs playing in the project.

---

.github/workflows/tf_apply.yml
terragrunt/.checkov.yml
terragrunt/aws/alarms/cloudwatch_breakglass.tf
terragrunt/aws/api/rds.tf
terragrunt/aws/tf_roles/main.tf
terragrunt/env/common/provider.tf

We clickopsed a severless v2 database and now would like to see how the TF reconciles that

fix: sync with clickops

---

terragrunt/.checkov.yml
terragrunt/aws/api/rds.tf

Reduce the database's ACU now that the upgrade has finished successfully.
- #371

chore: reduce database ACU

---

terragrunt/aws/api/vpc.tf

Switch to using a single NAT gateway to save money.

chore: use single NAT gateway

---

.github/workflows/build_and_push.yml
.github/workflows/ci_build_containers.yml

Using new version of trivy docker scan release. Fixing filename typo.

chore: using new version of trivy

---

README.md

chore: add doc for creating new scan

---

.github/workflows/docker-vulnerability-scan.yml

Run a nightly scan for Docker vulnerabilities and publish results to the GitHub Security section of the project.
- cds-snc/platform-core-services#209

feat: scheduled docker vulnerability scan
